// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// @ts-ignore
import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Member } from '../models';
/**
 * ListMembersApi - axios parameter creator
 * @export
 */
export const ListMembersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary get list of members in repository
         * @param {string} owner 
         * @param {string} repository 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMembers: async (owner: string, repository: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'owner' is not null or undefined
            if (owner === null || owner === undefined) {
                throw new RequiredError('owner','Required parameter owner was null or undefined when calling listMembers.');
            }
            // verify required parameter 'repository' is not null or undefined
            if (repository === null || repository === undefined) {
                throw new RequiredError('repository','Required parameter repository was null or undefined when calling listMembers.');
            }
            const localVarPath = `/repos/{owner}/{repository}/members`
                .replace(`{${"owner"}}`, encodeURIComponent(String(owner)))
                .replace(`{${"repository"}}`, encodeURIComponent(String(repository)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary get list of members in repository
         * @param {string} owner 
         * @param {string} repository 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMembers_1: async (owner: string, repository: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'owner' is not null or undefined
            if (owner === null || owner === undefined) {
                throw new RequiredError('owner','Required parameter owner was null or undefined when calling listMembers_1.');
            }
            // verify required parameter 'repository' is not null or undefined
            if (repository === null || repository === undefined) {
                throw new RequiredError('repository','Required parameter repository was null or undefined when calling listMembers_1.');
            }
            const localVarPath = `/repos/{owner}/{repository}/members`
                .replace(`{${"owner"}}`, encodeURIComponent(String(owner)))
                .replace(`{${"repository"}}`, encodeURIComponent(String(repository)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ListMembersApi - functional programming interface
 * @export
 */
export const ListMembersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary get list of members in repository
         * @param {string} owner 
         * @param {string} repository 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMembers(owner: string, repository: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Member>>> {
            const localVarAxiosArgs = await ListMembersApiAxiosParamCreator(configuration).listMembers(owner, repository, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary get list of members in repository
         * @param {string} owner 
         * @param {string} repository 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMembers_1(owner: string, repository: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Member>>> {
            const localVarAxiosArgs = await ListMembersApiAxiosParamCreator(configuration).listMembers_1(owner, repository, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ListMembersApi - factory interface
 * @export
 */
export const ListMembersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary get list of members in repository
         * @param {string} owner 
         * @param {string} repository 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMembers(owner: string, repository: string, options?: any): AxiosPromise<Array<Member>> {
            return ListMembersApiFp(configuration).listMembers(owner, repository, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary get list of members in repository
         * @param {string} owner 
         * @param {string} repository 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMembers_1(owner: string, repository: string, options?: any): AxiosPromise<Array<Member>> {
            return ListMembersApiFp(configuration).listMembers_1(owner, repository, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ListMembersApi - object-oriented interface
 * @export
 * @class ListMembersApi
 * @extends {BaseAPI}
 */
export class ListMembersApi extends BaseAPI {
    /**
     * 
     * @summary get list of members in repository
     * @param {string} owner 
     * @param {string} repository 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListMembersApi
     */
    public listMembers(owner: string, repository: string, options?: any) {
        return ListMembersApiFp(this.configuration).listMembers(owner, repository, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary get list of members in repository
     * @param {string} owner 
     * @param {string} repository 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListMembersApi
     */
    public listMembers_1(owner: string, repository: string, options?: any) {
        return ListMembersApiFp(this.configuration).listMembers_1(owner, repository, options).then((request) => request(this.axios, this.basePath));
    }

}
