apiVersion: apps/v1
kind: Deployment
metadata:
#  name: gitdata-rust-deployment
  namespace: gitdata
  labels:
    apptype: gitdata-rust
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: gitdata-rust
  template:
    metadata:
      labels:
        app: gitdata-rust
        apptype: gitdata-rust
    spec:
      containers:
        - name: gitdata-rust
          image: gitdatateam/gitdatarust:{{ .Values.tag }}
          imagePullPolicy: Always
          env:
            - name: JIAOZIFS_API_URL
              value: {{ .Values.api_url }}
          ports:
            - containerPort: 80
