apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitdata-rust
  namespace: gitdata
  annotations:
    meta.helm.sh/release-name: gitdata-rust
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,Content-Type,Authorization,Origin,Accept,Access-Control-Request-Method,Access-Control-Request-Headers"  # 允许的请求头
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-max-age: "86400"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Length,Content-Range"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    apptype: gitdata-rust
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release: gitdata-rust
spec:
  ingressClassName: {{.Values.ingress_name}}
  rules:
    - host: devcloud.gitdata.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitdata-rust-service
                port:
                  number: 80
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: jzfs-rust-service
                port:
                  number: 34513
