apiVersion: v1
kind: Service
metadata:
  name: gitdata-rust-service
  namespace: gitdata
  labels:
    apptype: gitdata-rust
spec:
  type: ClusterIP
  selector:
    app: gitdata-rust
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: jzfs-rust-service-external
  namespace: gitdata
spec:
  externalName: v1.jiaozifs.com
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  sessionAffinity: ClientIP