// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './apis/aksks-api';
export * from './apis/auth-api';
export * from './apis/branches-api';
export * from './apis/commit-api';
export * from './apis/common-api';
export * from './apis/group-api';
export * from './apis/list-members-api';
export * from './apis/member-api';
export * from './apis/mergerequest-api';
export * from './apis/objects-api';
export * from './apis/repo-api';
export * from './apis/repos-api';
export * from './apis/tags-api';
export * from './apis/wip-api';

