// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Aksk
 */
export interface Aksk {
    /**
     * 
     * @type {string}
     * @memberof Aksk
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Aksk
     */
    access_key: string;
    /**
     * 
     * @type {string}
     * @memberof Aksk
     */
    secret_key: string;
    /**
     * 
     * @type {string}
     * @memberof Aksk
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Aksk
     */
    created_at: number;
    /**
     * 
     * @type {number}
     * @memberof Aksk
     */
    updated_at: number;
}


