// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticationToken
 */
export interface AuthenticationToken {
    /**
     * a JWT token that could be used to authenticate requests
     * @type {string}
     * @memberof AuthenticationToken
     */
    token: string;
    /**
     * Unix Epoch in seconds
     * @type {number}
     * @memberof AuthenticationToken
     */
    token_expiration?: number;
}


