// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Blob
 */
export interface Blob {
    /**
     * 
     * @type {string}
     * @memberof Blob
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof Blob
     */
    repository_id: string;
    /**
     * 
     * @type {string}
     * @memberof Blob
     */
    check_sum: string;
    /**
     * 
     * @type {number}
     * @memberof Blob
     */
    type: number;
    /**
     * 
     * @type {number}
     * @memberof Blob
     */
    size: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Blob
     */
    properties: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof Blob
     */
    created_at: number;
    /**
     * 
     * @type {number}
     * @memberof Blob
     */
    updated_at: number;
}


