// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BlockStoreConfigAzure } from './block-store-config-azure';
import { BlockStoreConfigGs } from './block-store-config-gs';
import { BlockStoreConfigLocal } from './block-store-config-local';
import { BlockStoreConfigS3 } from './block-store-config-s3';

/**
 * 
 * @export
 * @interface BlockStoreConfig
 */
export interface BlockStoreConfig {
    /**
     * type of support storage type
     * @type {string}
     * @memberof BlockStoreConfig
     */
    type: BlockStoreConfigTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BlockStoreConfig
     */
    default_namespace_prefix?: string;
    /**
     * 
     * @type {BlockStoreConfigLocal}
     * @memberof BlockStoreConfig
     */
    local?: BlockStoreConfigLocal;
    /**
     * 
     * @type {BlockStoreConfigAzure}
     * @memberof BlockStoreConfig
     */
    azure?: BlockStoreConfigAzure;
    /**
     * 
     * @type {BlockStoreConfigGs}
     * @memberof BlockStoreConfig
     */
    gs?: BlockStoreConfigGs;
    /**
     * 
     * @type {BlockStoreConfigS3}
     * @memberof BlockStoreConfig
     */
    s3?: BlockStoreConfigS3;
}

/**
    * @export
    * @enum {string}
    */
export enum BlockStoreConfigTypeEnum {
    Local = 'local',
    Gs = 'gs',
    Azure = 'azure',
    S3 = 's3'
}



