// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Branch } from './branch';
import { Pagination } from './pagination';

/**
 * 
 * @export
 * @interface BranchList
 */
export interface BranchList {
    /**
     * 
     * @type {Pagination}
     * @memberof BranchList
     */
    pagination: Pagination;
    /**
     * 
     * @type {Array<Branch>}
     * @memberof BranchList
     */
    results: Array<Branch>;
}


