// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BranchCreation
 */
export interface BranchCreation {
    /**
     * 
     * @type {string}
     * @memberof BranchCreation
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BranchCreation
     */
    source: string;
}


