// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Change } from './change';

/**
 * 
 * @export
 * @interface ChangePair
 */
export interface ChangePair {
    /**
     * 
     * @type {string}
     * @memberof ChangePair
     */
    path: string;
    /**
     * 
     * @type {Change}
     * @memberof ChangePair
     */
    left?: Change;
    /**
     * 
     * @type {Change}
     * @memberof ChangePair
     */
    right?: Change;
    /**
     * 
     * @type {boolean}
     * @memberof ChangePair
     */
    is_conflict: boolean;
}


