// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Signature } from './signature';

/**
 * 
 * @export
 * @interface Commit
 */
export interface Commit {
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    repository_id: string;
    /**
     * 
     * @type {Signature}
     * @memberof Commit
     */
    author: Signature;
    /**
     * 
     * @type {Signature}
     * @memberof Commit
     */
    committer: Signature;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    merge_tag: string;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    tree_hash: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Commit
     */
    parent_hashes: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Commit
     */
    created_at: number;
    /**
     * 
     * @type {number}
     * @memberof Commit
     */
    updated_at: number;
}


