// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateRepository
 */
export interface CreateRepository {
    /**
     * 
     * @type {string}
     * @memberof CreateRepository
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRepository
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateRepository
     */
    visible?: boolean;
    /**
     * block storage config url encoded json
     * @type {string}
     * @memberof CreateRepository
     */
    blockstore_config?: string;
}


