// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateMergeRequest
 */
export interface CreateMergeRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateMergeRequest
     */
    target_branch_name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMergeRequest
     */
    source_branch_name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMergeRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMergeRequest
     */
    description?: string;
}


