// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginConfig
 */
export interface LoginConfig {
    /**
     * RBAC will remain enabled on GUI if \"external\".  That only works with an external auth service. 
     * @type {string}
     * @memberof LoginConfig
     */
    RBAC?: LoginConfigRBACEnum;
    /**
     * primary URL to use for login.
     * @type {string}
     * @memberof LoginConfig
     */
    login_url: string;
    /**
     * message to display to users who fail to login; a full sentence that is rendered in HTML and may contain a link to a secondary login method 
     * @type {string}
     * @memberof LoginConfig
     */
    login_failed_message?: string;
    /**
     * secondary URL to offer users to use for login.
     * @type {string}
     * @memberof LoginConfig
     */
    fallback_login_url?: string;
    /**
     * label to place on fallback_login_url.
     * @type {string}
     * @memberof LoginConfig
     */
    fallback_login_label?: string;
    /**
     * cookie names used to store JWT
     * @type {Array<string>}
     * @memberof LoginConfig
     */
    login_cookie_names: Array<string>;
    /**
     * URL to use for logging out.
     * @type {string}
     * @memberof LoginConfig
     */
    logout_url: string;
}

/**
    * @export
    * @enum {string}
    */
export enum LoginConfigRBACEnum {
    Simplified = 'simplified',
    External = 'external'
}



