// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MergeRequest
 */
export interface MergeRequest {
    /**
     * 
     * @type {string}
     * @memberof MergeRequest
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof MergeRequest
     */
    sequence: number;
    /**
     * 
     * @type {string}
     * @memberof MergeRequest
     */
    target_branch: string;
    /**
     * 
     * @type {string}
     * @memberof MergeRequest
     */
    source_branch: string;
    /**
     * 
     * @type {string}
     * @memberof MergeRequest
     */
    source_repo_id: string;
    /**
     * 
     * @type {string}
     * @memberof MergeRequest
     */
    target_repo_id: string;
    /**
     * 
     * @type {string}
     * @memberof MergeRequest
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof MergeRequest
     */
    merge_status: number;
    /**
     * 
     * @type {string}
     * @memberof MergeRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MergeRequest
     */
    author_id: string;
    /**
     * 
     * @type {number}
     * @memberof MergeRequest
     */
    created_at: number;
    /**
     * 
     * @type {number}
     * @memberof MergeRequest
     */
    updated_at: number;
}


