// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MergeMergeRequest
 */
export interface MergeMergeRequest {
    /**
     * 
     * @type {string}
     * @memberof MergeMergeRequest
     */
    msg: string;
    /**
     * use to record the resolution of the conflict, example({\"b/a.txt\":\"left\"})
     * @type {{ [key: string]: string; }}
     * @memberof MergeMergeRequest
     */
    conflict_resolve?: { [key: string]: string; };
}


