// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MergeRequest } from './merge-request';
import { Pagination } from './pagination';

/**
 * 
 * @export
 * @interface MergeRequestList
 */
export interface MergeRequestList {
    /**
     * 
     * @type {Pagination}
     * @memberof MergeRequestList
     */
    pagination: Pagination;
    /**
     * 
     * @type {Array<MergeRequest>}
     * @memberof MergeRequestList
     */
    results: Array<MergeRequest>;
}


