// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ObjectStats
 */
export interface ObjectStats {
    /**
     * 
     * @type {string}
     * @memberof ObjectStats
     */
    path: string;
    /**
     * 
     * @type {number}
     * @memberof ObjectStats
     */
    path_mode?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectStats
     */
    checksum: string;
    /**
     * 
     * @type {number}
     * @memberof ObjectStats
     */
    size_bytes?: number;
    /**
     * Unix Epoch in seconds
     * @type {number}
     * @memberof ObjectStats
     */
    mtime: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ObjectStats
     */
    metadata?: { [key: string]: string; };
    /**
     * Object media type
     * @type {string}
     * @memberof ObjectStats
     */
    content_type?: string;
}


