// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Credential } from './credential';

/**
 * S3AuthInfo holds S3-style authentication.
 * @export
 * @interface S3AuthInfo
 */
export interface S3AuthInfo {
    /**
     * 
     * @type {Credential}
     * @memberof S3AuthInfo
     */
    credentials: Credential;
}


