// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TagCreation
 */
export interface TagCreation {
    /**
     * 
     * @type {string}
     * @memberof TagCreation
     */
    name: string;
    /**
     * target branch name or commit hex, first try branch and then commit
     * @type {string}
     * @memberof TagCreation
     */
    target: string;
    /**
     * 
     * @type {string}
     * @memberof TagCreation
     */
    message?: string;
}


