// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    repository_id: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    creator_id: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    target: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof Tag
     */
    created_at: number;
    /**
     * 
     * @type {number}
     * @memberof Tag
     */
    updated_at: number;
}


