// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateWip
 */
export interface UpdateWip {
    /**
     * 
     * @type {string}
     * @memberof UpdateWip
     */
    base_commit?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWip
     */
    current_tree?: string;
}


