// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    current_sign_in_at?: number;
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    last_sign_in_at?: number;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    current_sign_in_ip?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    last_sign_in_ip?: string;
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    created_at: number;
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    updated_at: number;
}


