// tslint:disable
/**
 * JZConsole
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WebIdentity
 */
export interface WebIdentity {
    /**
     * 
     * @type {number}
     * @memberof WebIdentity
     */
    session_duration: number;
    /**
     * 
     * @type {number}
     * @memberof WebIdentity
     */
    session_expiry_window: number;
}


